#ifndef _FTTP_ENUM_H_
#define _FTTP_ENUM_H_

enum fttp_service {
	FTTP_SERVICE_USER_REQ = 0,
	FTTP_SERVICE_USER_RSP,
	FTTP_SERVICE_SEND_TEXT,
	FTTP_SERVICE_SEND_FILE,
	FTTP_SERVICE_LINK_TEST,
	FTTP_SERVICE_MAX
};

enum pdu_type {
	FTTP_PDU_REQ = 0,
	FTTP_PDU_RSP,
	FTTP_PDU_SEGMENT_RSP,
	FTTP_PDU_ERROR,
	FTTP_PDU_REJECT,
	FTTP_PDU_ABORT,
	FTTP_PDU_TYPE_MAX
};

#endif
