#ifndef _FTTP_ENUM_H_
#define _FTTP_ENUM_H_

enum fttp_service {
	FTTP_SERVICE_USER_REQ = 0,
	FTTP_SERVICE_USER_RSP,
	FTTP_SERVICE_TRANS_TEXT,
	FTTP_SERVICE_TRANS_FILE,
	FTTP_SERVICE_LINK_TEST,
	FTTP_SERVICE_MAX
};

enum pdu_type {
	FTTP_PDU_REQ = 0,
	FTTP_PDU_RSP_SIMPLE,
	FTTP_PDU_RSP_COMPLEX,
	FTTP_PDU_ERROR,
	FTTP_PDU_TYPE_MAX
};

enum fttp_user_type {
	FTTP_USER_BOY = 0,
	FTTP_USER_GIRL = 1,
	FTTP_USER_ROOM = 2
};

enum fttp_value_tag {
	FTTP_VALUE_UINT = 0,
	FTTP_VALUE_STRING,
	FTTP_VALUE_ENUM
};
#endif
